### ISSUE TITLE
Relative PATH is broken

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jenkins_shared_ci_utils#61]
This breaks HSTCAL tests. 

https://github.com/spacetelescope/hstcal/blob/7810f2681d6fecfe7a28e46366606138965ccff5/JenkinsfileRT#L27

See https://plwishmaster.stsci.edu:8081/job/RT/job/hstcal/test_results_analyzer/ for more details.

```
+ calacs.e --version
/srv/jenkins/workspace/RT/hstcal/clone@tmp/durable-9617e11a/script.sh: line 1: calacs.e: command not found
```

**Comment by mdlpstsci** [comment]
Thanks Pey-Lian. I did copy out the relevant text from the Travis and Jenkins complaints and sent them to Joe a while ago.  I should have cc'ed you!

**Comment by pllim** [comment]
Yes, the Travis CI is another matter as well. I just added a weekly cron job on the Travis side.

**Comment by pllim** [comment]
Fixed downstream in HSTCAL.
