### ISSUE TITLE
Feature Request: Open GitHub issue when nightly tests failed

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jenkins_shared_ci_utils#9]
From @jdavies-st -- When nightly tests failed for `jwst` in Jenkins, it should open a new issue on `jwst` repo with some description and a link to the failed tests.

https://developer.github.com/v3/issues/#create-an-issue

~~There is also https://developer.github.com/v4/ if you are adventurous...~~ GraphQL not yet support issue creation. See https://platform.github.community/t/is-there-a-way-to-create-an-issue-with-graphql-api/3574

**Comment by rendinam** [comment]
Functionality provided in version `1.2.6`.
